### ISSUE TITLE
rating system

### ISSUE THREAD

**Issue by Phantom05** [Phantom05/dev.config#27]
```html
                  <span class="main__main_slide_rating_box">☆☆☆☆☆
                    <span class="main__main_slide_rating_color" data-rating="<%= slide_info.rating*10 %>">
                      ★★★★★
                    </span>
                  </span>

```

```css
.main__main_slide_rating_box {
  position: relative;
}

.main__main_slide_rating_color {
  position: absolute;
  left: 0;
  top: 2px;
  overflow: hidden;

}

.main__main_slide_rating_dim {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
}
```
```js
  Array.from(document.querySelectorAll('[data-rating]')).map(list => {
    console.log(list);
    list.style.width = `${list.getAttribute('data-rating')}%`;
  })
```
